const listBtnThayAo = document.querySelectorAll('#btn-thayAo')
const listBtnThayVay = document.querySelectorAll('#btn-thayVay')
const listBtnThayGiay = document.querySelectorAll('#btn-thayGiay')
const listBtnThayTui = document.querySelectorAll('#btn-thayTui')
const listBtnThayVongCo = document.querySelectorAll('#btn-thayVongCo')
const listBtnThayKieuToc = document.querySelectorAll('#btn-thayKieuToc')
const listBtnThayNen = document.querySelectorAll('#btn-thayNen')